apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: iot-integration-test-pipeline
spec:
  description: >-
    Expects a list of container images to be provided via the SNAPSHOT parameter.
  params:
    - name: SNAPSHOT
      description: A list of fdo container images that should undergo testing
      default: "quay.io/fedora/fedora-bootc:43"
      type: string
    - name: GIT_URL
      description: URL of the GIT repository that contains the tests.
      default: "https://github.com/yih-redhat/fedora-iot-konflux.git"
      type: string
    - name: GIT_REF
      default: "main"
      description: Branch of the git repository used containing the tests
      type: string
  tasks:
    - name: iot-integration-test
      taskRef:
        resolver: git
        params:
          - name: url
            value: $(params.GIT_URL)
          - name: revision
            value: $(params.GIT_REF)
          - name: pathInRepo
            value: .tekton/iot-test-task.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: GIT_URL
          value: $(params.GIT_URL)
        - name: GIT_REF
          value: $(params.GIT_REF)
      timeout: "2h"
